---
- name: Testing andrewrothstein.transmission
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'transmission-daemon --version'
      ansible.builtin.command: transmission-daemon --version
      changed_when: false
      register: transmission_test_output
    - name: Output from 'transmission-daemon --version'
      ansible.builtin.debug:
        msg: '{{ transmission_test_output.stdout }}'
