---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.gcc_toolbox
  ansible.builtin.include_role:
    name: andrewrothstein.gcc_toolbox
- name: Installing andrewrothstein.epel
  ansible.builtin.include_role:
    name: andrewrothstein.epel
- name: Installing andrewrothstein.cmake
  ansible.builtin.include_role:
    name: andrewrothstein.cmake
- name: Installing andrewrothstein.openssl
  ansible.builtin.include_role:
    name: andrewrothstein.openssl
  vars:
    openssl_include_dev_pkgs: true
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Installing OS dep pkgs...
  become: true
  become_user: root
  with_items: '{{ transmission_dep_pkgs | default([]) }}'
  ansible.builtin.package:
    name: '{{ item }}'
    state: present

- name: Check for source dir at {{ transmission_src_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ transmission_src_dir }}'
  changed_when: false
  register: transmission_binary
- name: Downloading tand unarchiving ransmission source to {{ transmission_src_dir }}
  when: not transmission_binary.stat.exists
  block:
    - name: Downloading {{ transmission_txz_url }}...
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ transmission_txz_url }}'
        dest: '{{ transmission_tmp_txz }}'
        checksum: '{{ transmission_checksum }}'
        mode: '644'

    - name: Unarchiving {{ transmission_tmp_txz }}...
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ transmission_tmp_txz }}'
        dest: '{{ transmission_parent_src_dir }}'
        creates: '{{ transmission_src_dir }}'
  always:
    - name: Rm -f {{ transmission_tmp_txz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ transmission_tmp_txz }}'
        state: absent

- name: Mkdir {{ transmission_build_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ transmission_build_dir }}'
    state: directory
    mode: '755'

- name: Executing '{{ transmission_cmake_cmd }}'
  become: true
  become_user: root
  ansible.builtin.command: '{{ transmission_cmake_cmd }}'
  args:
    chdir: '{{ transmission_build_dir }}'
    creates: '{{ transmission_makefile }}'

- name: Executing '{{ transmission_make_cmd }}'
  become: true
  become_user: root
  ansible.builtin.command: '{{ transmission_make_cmd }}'
  args:
    chdir: '{{ transmission_build_dir }}'
    creates: '{{ transmission_build_exe }}'

- name: Executing '{{ transmission_make_install_cmd }}'
  become: true
  become_user: root
  ansible.builtin.command: '{{ transmission_make_install_cmd }}'
  args:
    chdir: '{{ transmission_build_dir }}'
    creates: '{{ transmission_exe }}'
