---
- include_role:
    name: andrewrothstein.unarchivedeps
- include_role:
    name: andrewrothstein.gcc_toolbox
- include_role:
    name: andrewrothstein.epel
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: check for install...
  become: true
  stat:
    path: /usr/local/bin/transmission-daemon
  changed_when: false
  register: transmission_binary
- when: not transmission_binary.stat.exists
  block:
    - name: installing OS dep pkgs...
      become: true
      become_user: root
      with_items: '{{ transmission_dep_pkgs | default([]) }}'
      package:
        name: '{{ item }}'
        state: present

    - name: downloading {{ transmission_txz_url }}...
      become: true
      become_user: root
      get_url:
        url: '{{ transmission_txz_url }}'
        dest: '{{ transmission_tmp_txz }}'
        checksum: '{{ transmission_checksum }}'
        mode: 0644

    - name: unarchiving {{ transmission_tmp_txz }}...
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ transmission_tmp_txz }}'
        dest: '{{ transmission_parent_src_dir }}'
        creates: '{{ transmission_src_dir }}'

    - name: '{{ transmission_src_configure }}...'
      become: true
      become_user: root
      command: '{{ transmission_src_configure }}'
      args:
        chdir: '{{ transmission_src_dir }}'
        creates: '{{ transmission_src_Makefile }}'

    - name: make (in {{ transmission_src_dir }})
      become: true
      become_user: root
      command: make
      args:
        chdir: '{{ transmission_src_dir }}'
        creates: '{{ transmission_src_dir }}/daemon/transmission-daemon'

    - name: make install (in {{ transmission_src_dir }})
      become: true
      become_user: root
      command: make install
      args:
        chdir: '{{ transmission_src_dir }}'
        creates: /usr/local/bin/transmission-daemon
  always:
    - name: cleanup...
      become: true
      become_user: root
      with_items:
        - '{{ transmission_src_dir }}'
        - '{{ transmission_tmp_txz }}'
      file:
        path: '{{ item }}'
        state: absent
