---
- name: andrewrothstein.unarchivedeps
  version: 3.0.3
- name: andrewrothstein.gcc_toolbox
  version: 2.0.5
- name: andrewrothstein.epel
  version: v1.1.11
- name: andrewrothstein.cmake
  version: v2.2.18
- name: andrewrothstein.openssl
  version: v1.2.1
