---
- name: andrewrothstein.unarchivedeps
  version: 3.0.0
- name: andrewrothstein.gcc_toolbox
  version: 2.0.3
- name: andrewrothstein.epel
  version: v1.1.9
- name: andrewrothstein.cmake
  version: v2.2.4
